/* ─────────────────────────────────────────────────────────────
   bindings.ts — the fixed IPC contract (PLAN §4)

   In the Tauri build this file is generated by tauri-specta from
   the Rust core. In this standalone UI build it is hand-maintained
   to match §4 exactly, and implemented by mockCore.ts. The UI may
   ONLY call what is declared here — swap the implementation, never
   the shape.
   ───────────────────────────────────────────────────────────── */

import type { Anchor } from "./hud";

// ── auth ──────────────────────────────────────────────────────

export interface Account {
  uuid: string;
  username: string;
  /** hue used to render the mock face (0..360) — fallback when skinUrl is null */
  skinHue: number;
  /** 64×64 skin texture for the 3D render — real core sends the session skin URL */
  skinUrl: string | null;
  source: "microsoft" | "imported" | "offline";
  capes: string[];
}

export interface DeviceCodePrompt {
  session: string;
  userCode: string;
  verificationUri: string;
  expiresIn: number;
}

export type AuthStatus =
  | { state: "pending" }
  | { state: "done"; account: Account }
  | { state: "error"; message: string };

// ── versions / instances ──────────────────────────────────────

export interface VersionSummary {
  id: string;
  type: "release" | "snapshot";
  releaseTime: string;
  isTarget: boolean;
}

export type InstallStage =
  | "manifest"
  | "libraries"
  | "assets"
  | "jre"
  | "fabric"
  | "mods"
  | "done";

export interface Instance {
  id: string;
  name: string;
  versionId: string;
  loader: "fabric" | "vanilla";
  installed: boolean;
  installing: { stage: InstallStage; pct: number } | null;
  memoryMb: number;
  iconHue: number;
  createdAt: string;
  lastPlayedAt: string | null;
  quickPlayServer: string | null;
}

export interface InstanceSpec {
  name: string;
  versionId: string;
  loader: "fabric" | "vanilla";
  memoryMb?: number;
  iconHue?: number;
}

export interface InstancePatch {
  name?: string;
  memoryMb?: number;
  quickPlayServer?: string | null;
}

// ── mods ──────────────────────────────────────────────────────

export interface Mod {
  id: string;
  name: string;
  version: string;
  description: string;
  kind: "hud" | "perf" | "lib";
  ours: boolean;
  compatible: boolean;
  note: string | null;
}

export interface ModCatalog {
  mods: Mod[];
}

export interface InstalledMod extends Mod {
  enabled: boolean;
  favorite: boolean;
  /** the jar is in the instance's mods dir right now */
  installed: boolean;
  file?: string;
}

// ── launch ────────────────────────────────────────────────────

export interface LaunchOpts {
  server?: string;
}

export type GameStateValue = "idle" | "starting" | "running" | "crashed" | "closed";

export interface GameState {
  state: GameStateValue;
  sessionId: string | null;
  instanceId: string | null;
  server: string | null;
  startedAt: number | null;
  exitCode: number | null;
}

/** `OURS` is a line our own client logged — the core tags it off the `(Fullmoon/…)` logger name. */
export type LogLevel = "INFO" | "WARN" | "ERROR" | "DEBUG" | "OURS";

// ── cosmetics / hud ───────────────────────────────────────────

export type CosmeticSlot = "cape" | "wings" | "trail";

export type Rarity = "common" | "rare" | "epic" | "legendary";

export interface Cosmetic {
  id: string;
  slot: CosmeticSlot;
  name: string;
  rarity: Rarity;
  hue: number;
  desc: string;
  /** 64×32 cape texture for the 3D preview — cape slot only, null for wings/trail */
  capeUrl: string | null;
}

export type Loadout = Record<CosmeticSlot, string | null>;

/** One element as the client stores it: a nine-way anchor and a pixel offset measured from it.
 *  The vocabulary and the arithmetic are mirrored in core/hud.ts from the mod's own source. */
export interface HudElementState {
  enabled: boolean;
  anchor: Anchor;
  offsetX: number;
  offsetY: number;
  scale: number;
}

/** Keyed by element id, because that is the only thing the two editors agree to key on — the
 *  order the map arrives in is the serialiser's, and never the order to render. */
export interface HudConfig {
  elements: Record<string, HudElementState>;
  gridSnap: number;
}

// ── settings ──────────────────────────────────────────────────

export interface Settings {
  javaPath: string | null;
  javaArgs: string;
  memoryMb: number;
  concurrency: number;
  theme: "dark" | "light";
  accent: string;
  language: "ko" | "en";
  telemetry: boolean;
}

export interface JavaRuntime {
  path: string;
  version: string;
  vendor: string;
  arch: string;
  recommended: boolean;
}

// ── home ──────────────────────────────────────────────────────

export interface NewsItem {
  id: string;
  tag: "update" | "event" | "dev" | "cosmetic";
  title: string;
  summary: string;
  date: string;
  hue: number;
  featured: boolean;
}

/** The server wallet, as the economy backend reports it. Auth is the
 *  bridge session token — a launcher sees a wallet only while its player
 *  is actually on the network (PLAN §1). */
export interface WalletInfo {
  currency: string;
  balance: number;
  /** ISO timestamp of the last mutation the backend knows about */
  updatedAt: string;
}

export interface WalletTx {
  /** signed amount — positive is income, negative is spend */
  delta: number;
  /** the economy backend's reason code ("discord.daily", "casino.jackpot…") */
  reason: string;
  /** display label already resolved server-side (TX_LABELS vocabulary) */
  label: string;
  balanceAfter: number | null;
  at: string;
}

export interface ServerEntry {
  id: string;
  name: string;
  address: string;
  motd: string;
  players: number;
  maxPlayers: number;
  pingMs: number;
  hue: number;
}

/** What the server itself answered. `online: false` carries the reason. */
export interface ServerStatus {
  online: boolean;
  motd: string;
  players: number;
  maxPlayers: number;
  pingMs: number;
  version: string;
  favicon?: string;
  error?: string;
}

// ── events ────────────────────────────────────────────────────

export interface CoreEvents {
  "auth://device": { userCode: string; verificationUri: string; expiresIn: number };
  "download://progress": {
    taskId: string;
    file: string;
    done: number;
    total: number;
    bytesPerSec: number;
  };
  "install://stage": { instanceId: string; stage: InstallStage; pct: number };
  "game://log": { sessionId: string; level: LogLevel; line: string };
  "game://state": {
    sessionId: string;
    state: GameStateValue;
    exitCode?: number;
  };
}

export type CoreEventName = keyof CoreEvents;

// ── the command surface (PLAN §4, verbatim shape) ─────────────

export interface PinionCore {
  // auth
  auth_begin_device_code(): Promise<DeviceCodePrompt>;
  auth_poll(session: string): Promise<AuthStatus>;
  auth_login_authcode(): Promise<Account>;
  auth_import_official(): Promise<Account[]>;
  auth_list(): Promise<Account[]>;
  auth_select(uuid: string): Promise<void>;
  auth_remove(uuid: string): Promise<void>;
  auth_refresh(uuid: string): Promise<Account>;
  auth_add_offline(username: string): Promise<Account>;

  // versions / instances
  /** what the last successful fetch left on disk; never touches the network */
  versions_cached(): Promise<VersionSummary[]>;
  versions_manifest(): Promise<VersionSummary[]>;
  instances_list(): Promise<Instance[]>;
  instance_create(spec: InstanceSpec): Promise<Instance>;
  instance_update(id: string, patch: InstancePatch): Promise<Instance>;
  instance_delete(id: string): Promise<void>;
  instance_install(id: string): Promise<string>; // -> taskId

  // mods
  mods_available(): Promise<ModCatalog>;
  /** live status straight from the servers, keyed by the address asked for */
  servers_ping(addresses: string[]): Promise<Record<string, ServerStatus>>;

  mods_list(instanceId: string): Promise<InstalledMod[]>;
  mod_toggle(instanceId: string, modId: string, enabled: boolean): Promise<void>;
  mod_favorite(instanceId: string, modId: string, favorite: boolean): Promise<void>;

  // launch
  launch(instanceId: string, opts?: LaunchOpts): Promise<string>; // -> sessionId
  launch_quickplay(instanceId: string, server: string): Promise<string>;
  game_kill(sessionId: string): Promise<void>;
  game_status(): Promise<GameState>;
  /** What the current run has already printed, for a console that opens late. */
  game_log(): Promise<{ sessionId: string; level: LogLevel; line: string }[]>;

  // cosmetics / hud
  cosmetics_catalog(): Promise<Cosmetic[]>;
  cosmetics_equipped(uuid: string): Promise<Loadout>;
  cosmetics_equip(uuid: string, slot: CosmeticSlot, itemId: string | null): Promise<void>;
  hud_get(instanceId: string): Promise<HudConfig>;
  hud_set(instanceId: string, cfg: HudConfig): Promise<void>;
  /** Put the catalogue default back and hand it over: the defaults live in the core, and a UI
   *  that restated them would be the drift this asks about. */
  hud_reset(instanceId: string): Promise<HudConfig>;

  // settings
  settings_get(): Promise<Settings>;
  settings_set(patch: Partial<Settings>): Promise<Settings>;
  java_detect(): Promise<JavaRuntime[]>;
  /** physical RAM in MB; 0 when the platform will not say */
  system_memory_mb(): Promise<number>;

  // home
  news_feed(): Promise<NewsItem[]>;
  servers_list(): Promise<ServerEntry[]>;
  servers_save(list: ServerEntry[]): Promise<void>;

  // economy — fullmoon; live only while the bridge session token is fresh
  economy_wallet(): Promise<WalletInfo>;
  economy_transactions(): Promise<WalletTx[]>;

  // event subscription — returns an unsubscribe fn
  on<E extends CoreEventName>(event: E, cb: (payload: CoreEvents[E]) => void): () => void;
}
